/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    #[doc = "if party == 1 (ALICE), we are hosting, so `remote_addr` can be nullptr. Otherwise (BOB), `remote_addr` must be non-nullptr."]
    #[doc = "Return number of bytes sent."]
    pub fn emp_rot(
        party: ::std::os::raw::c_int,
        remote_addr: *const ::std::os::raw::c_char,
        port: ::std::os::raw::c_int,
        count: ::std::os::raw::c_longlong,
        mode: ::std::os::raw::c_int,
        data0: *mut ::std::os::raw::c_uchar,
        data1: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_ulonglong;
}
